Add decorators
IsmaelMastronardi/school-library pull request #2
Opened 2023-10-03 22:37 UTC by IsmaelMastronardi

2023-10-03 23:40 UTC, Owusu-Desmond requested changes
Hi @IsmaelMastronardi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-03 23:40 UTC, Owusu-Desmond commented on person.rb
> +    super
- [ ] To fix this issue in your project, please remove the `super` keyword from your initialize method. The initialize method calls the parent class's initialize method with the same arguments, but your parent class does not have an initialize method. This caused an error when I tested your project. Simply removing the `super` keyword will resolve this problem.
  
  ![image](https://github.com/IsmaelMastronardi/school-library/assets/92303891/1bd6a14b-b9b0-4c1a-a095-1b6b60150709)

2023-10-03 23:40 UTC, Owusu-Desmond commented on base_decorator.rb
> +    super
- [ ] To fix this issue in your project, please remove the `super` keyword from your initialize method. The initialize method calls the parent class's initialize method with the same arguments, but your parent class does not have an initialize method. This caused an error when I tested your project. Simply removing the `super` keyword will resolve this problem. :blush: 
    
  ![image](https://github.com/IsmaelMastronardi/school-library/assets/92303891/40118d40-a78d-4856-adcd-407bc93f5542)

2023-10-04 00:33 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @IsmaelMastronardi , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done fixing the error that was preventing your code from running. 🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 01:15 UTC, merged